baseUrl=https://automationexercise.com/
loginPage=https://automationexercise.com/login
pageTitle=Automation Exercise - Signup / Login
HomeUrl=https://automationexercise.com/
logoutText= Logout
textInTsheirtPage =MEN - TSHIRTS PRODUCTS
cartPage=https://automationexercise.com/view_cart




